name: my_flutter_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.5.2
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Добавим настройку локализаций
  generate: true
  assets:
    - assets/

  localizations:
    delegates:
      - flutter_localizations
